# Generated by Django 5.1.4 on 2025-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='horse_images/')),
            ],
        ),
    ]
