# Generated by Django 5.1.4 on 2025-04-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_horsedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsedata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
