# Generated by Django 5.1.4 on 2025-04-28 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_horsedata_age_alter_horsedata_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsedata',
            name='users',
            field=models.ManyToManyField(related_name='horses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.horsedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
