# Generated by Django 5.1.4 on 2025-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
