# Generated by Django 5.1.4 on 2025-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_is_staff_user_lang_delete_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, default='hu', max_length=2, null=True),
        ),
    ]
