# Generated by Django 5.1.4 on 2025-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_staff_alter_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
