# Generated by Django 5.1.4 on 2025-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_horsedata_created_at_horsedata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsedata',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
