# Generated by Django 5.1.4 on 2026-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_horsedata_breed_horsedata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsedata',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='horse_videos/'),
        ),
    ]
