export enum DataNameModel {
  HORSE_NAME = "name",
  HORSE_GENDER = "gender",
  HORSE_BREED = "breed",
  HORSE_AGE = "age",
  HORSE_WEIGHT = "weight",
  HORSE_DESC = "desc",
  HORSE_IMAGE = "image",
  USER_NAME = "name",
  USER_PASSWORD = "password",
  ENGLISH = "en",
  HUNGARIAN = "hu",
  GERMAN = "de",
  JAPANESE = "ja",
  ACCESS_TOKEN = "accessToken",
  REFRESH_TOKEN = "refreshToken",
}
